import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Button } from "../components/ui/button.js";
import { BookOpen, Calendar, Clock, Award, CheckCircle2, GraduationCap } from "lucide-react";
const accentColor = "#C5A467";
const accentHoverColor = "#B08F55";
const primaryTextLight = "text-[#2A0F0F]";
const secondaryTextLight = "text-[#4A1F1F]";
const primaryTextDark = "dark:text-[#FFF8F0]";
const secondaryTextDark = "dark:text-[#E0D6C3]/90";
const mutedTextLight = "text-gray-500";
const mutedTextDark = "dark:text-gray-400";
const inputBgLight = "bg-[#FFF8F0]";
const inputBgDark = "dark:bg-gray-800";
const contentBgLight = "bg-white";
const contentBgDark = "dark:bg-gray-900";
const inputBorderLight = "border-[#E0D6C3]";
const inputBorderDark = "dark:border-gray-700";
const focusRingAccent = `focus:ring-[${accentColor}]`;
const focusBorderAccent = `focus:border-[${accentColor}] dark:focus:border-[${accentColor}]`;
const cardBgLight = "bg-white";
const cardBgDark = "dark:bg-gray-900";
const cardBorder = `border border-[#C5A467]/20 dark:border-[#C5A467]/30`;
const sectionBgLight = "bg-[#FFF8F0]";
const sectionBgDark = "dark:bg-gray-950";
const altSectionBgLight = "bg-[#F4EDE4]";
const altSectionBgDark = "dark:bg-gray-900";
export default function ProgramOverviewPage() {
    return (_jsxs("div", { className: `flex flex-col min-h-screen ${sectionBgLight} ${sectionBgDark}`, children: [_jsxs("section", { className: "w-full py-16 md:py-28 lg:py-36 bg-gradient-to-br from-[#2A0F0F] to-[#4A1F1F] dark:from-gray-900 dark:to-gray-800 relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 bg-[url('/path-to-subtle-cross-pattern.svg')] bg-repeat opacity-10 dark:opacity-5" }), _jsx("div", { className: "container relative px-4 md:px-6 z-10", children: _jsx("div", { className: "flex flex-col items-center space-y-4 text-center", children: _jsxs("div", { className: "space-y-3", children: [_jsx("h1", { className: "text-4xl text-[#FFF8F0] font-bold font-serif tracking-tight sm:text-5xl md:text-6xl lg:text-7xl/none", children: "Program Overview" }), _jsx("p", { className: "mx-auto max-w-[750px] text-[#E0D6C3] md:text-xl lg:text-lg", children: "A comprehensive guide to our Certificate in Apostolic & Evangelical Theology." })] }) }) })] }), _jsx("section", { className: `w-full py-16 md:py-24 lg:py-32 ${sectionBgLight} ${sectionBgDark}`, children: _jsx("div", { className: "container px-4 md:px-6", children: _jsxs("div", { className: "grid gap-10 lg:grid-cols-2 lg:gap-16 xl:gap-20", children: [_jsxs("div", { className: "space-y-6 pl-4", children: [_jsx("h2", { className: `text-3xl font-bold font-serif tracking-tight ${primaryTextLight} ${primaryTextDark}`, children: "Program Structure" }), _jsx("p", { className: `${secondaryTextLight} ${secondaryTextDark} text-lg`, children: "Our certificate program is structured to provide a comprehensive understanding of Apostolic and Evangelical theology through six sequential courses." }), _jsx("div", { className: "grid gap-4", children: [
                                            { icon: Calendar, title: "Duration", desc: "6 months total (6 courses, 4 weeks each)" },
                                            { icon: Clock, title: "Study Time", desc: "Approx. 10-12 hours per week" },
                                            { icon: Award, title: "Credits", desc: "39 ECTS total (6.5 ECTS per course)" },
                                            { icon: BookOpen, title: "Delivery", desc: "100% online with video lectures, readings, and assignments" },
                                        ].map((item, index) => (_jsxs("div", { className: `flex items-start gap-4 p-4 rounded-lg ${cardBgLight} ${cardBgDark} ${cardBorder} shadow-sm`, children: [_jsx(item.icon, { className: `h-6 w-6 text-[${accentColor}] mt-1 flex-shrink-0` }), _jsxs("div", { children: [_jsx("h3", { className: `font-semibold ${primaryTextLight} ${primaryTextDark}`, children: item.title }), _jsx("p", { className: `text-sm ${mutedTextLight} ${mutedTextDark}`, children: item.desc })] })] }, index))) })] }), _jsxs("div", { className: "space-y-6 pr-4", children: [_jsx("h2", { className: `text-3xl font-bold font-serif tracking-tight ${primaryTextLight} ${primaryTextDark}`, children: "Learning Approach" }), _jsx("p", { className: `${secondaryTextLight} ${secondaryTextDark} text-lg`, children: "Our program follows a structured, sequential learning approach to ensure you build a solid foundation." }), _jsx("ul", { className: "space-y-3", children: [
                                            "Courses must be taken in sequence.",
                                            "Weekly content unlocks progressively.",
                                            "Must complete current week's materials before accessing next week.",
                                            "Biannual intakes (January and July start dates).",
                                            "Cohort-based learning with peer interaction forums.",
                                            "Mid-cohort entry: Complete the current cohort's remaining lessons. Finish any missed lessons during the next cohort intake (free of charge) to receive your certificate."
                                        ].map((item, index) => (_jsxs("li", { className: "flex items-start gap-3", children: [_jsx(CheckCircle2, { className: `h-5 w-5 text-[${accentColor}] mt-0.5 flex-shrink-0` }), _jsx("span", { className: `${secondaryTextLight} ${secondaryTextDark}`, children: item })] }, index))) }), _jsxs("div", { className: "pt-4", children: [_jsx("h3", { className: `font-semibold mb-3 ${primaryTextLight} ${primaryTextDark}`, children: "Weekly Learning Components" }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm", children: [
                                                    "Video Lectures", "Reading Materials", "Quizzes & Assignments", "Discussion Forums"
                                                ].map((item, index) => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: `h-2.5 w-2.5 rounded-full bg-[${accentColor}]` }), _jsx("span", { className: `${secondaryTextLight} ${secondaryTextDark}`, children: item })] }, index))) })] })] })] }) }) }), _jsx("section", { className: `w-full py-16 md:py-24 lg:py-32 ${altSectionBgLight} ${altSectionBgDark}`, children: _jsxs("div", { className: "container px-4 md:px-6", children: [_jsx("div", { className: "flex flex-col items-center space-y-4 text-center mb-12", children: _jsxs("div", { className: "space-y-2", children: [_jsx("h2", { className: `text-3xl font-bold font-serif tracking-tight ${primaryTextLight} ${primaryTextDark}`, children: "Certification" }), _jsx("p", { className: `mx-auto max-w-[700px] md:text-xl ${secondaryTextLight} ${secondaryTextDark}`, children: "Upon successful completion of all program requirements." })] }) }), _jsxs("div", { className: "flex flex-col md:flex-row gap-8 lg:gap-12 items-center justify-center", children: [_jsx("div", { className: "flex-1 max-w-md w-full", children: _jsx("div", { className: `aspect-[4/3] relative ${sectionBgLight} ${sectionBgDark} rounded-lg shadow-lg flex items-center justify-center p-4 border-4 border-double border-[${accentColor}] dark:border-[${accentHoverColor}]`, children: _jsxs("div", { className: `border border-dashed border-[${accentColor}]/50 dark:border-[${accentHoverColor}]/50 p-6 w-full h-full flex flex-col items-center justify-center text-center`, children: [_jsx(GraduationCap, { className: `h-12 w-12 text-[${accentColor}] mb-4` }), _jsx("h3", { className: `text-lg font-semibold font-serif ${primaryTextLight} ${primaryTextDark}`, children: "Certificate in" }), _jsx("h3", { className: `text-xl font-bold font-serif mb-2 ${primaryTextLight} ${primaryTextDark}`, children: "Apostolic & Evangelical Theology" }), _jsx("p", { className: `text-xs mt-3 ${secondaryTextLight} ${secondaryTextDark}`, children: "Awarded by the International Apostolic Church" }), _jsx("p", { className: `text-sm font-semibold mt-1 ${primaryTextLight} ${primaryTextDark}`, children: "39 ECTS Credits" })] }) }) }), _jsxs("div", { className: "flex-1 max-w-md space-y-4", children: [_jsx("h3", { className: `text-xl font-semibold ${primaryTextLight} ${primaryTextDark}`, children: "What You'll Receive" }), _jsx("ul", { className: "space-y-3", children: [
                                                "Digital certificate suitable for printing (with unique ID)",
                                                "Official transcript detailing courses and grades",
                                                "Recognition of completion from the Apostolic Church International",
                                                "Solid foundation for ministry roles or further theological studies",
                                            ].map((item, index) => (_jsxs("li", { className: "flex items-start gap-3", children: [_jsx(CheckCircle2, { className: `h-5 w-5 text-[${accentColor}] mt-0.5 flex-shrink-0` }), _jsx("span", { className: `${secondaryTextLight} ${secondaryTextDark}`, children: item })] }, index))) }), _jsx("div", { className: "pt-4", children: _jsx("p", { className: `italic ${mutedTextLight} ${mutedTextDark}`, children: "\"Study to show yourself approved unto God...\" \u2013 2 Timothy 2:15" }) })] })] })] }) }), _jsxs("section", { className: "w-full py-16 md:py-24 lg:py-28 bg-[#2A0F0F] dark:bg-black relative text-[#FFF8F0]", children: [_jsx("div", { className: "absolute inset-x-0 top-0 h-2 bg-gradient-to-b from-[#C5A467]/30 to-transparent" }), _jsx("div", { className: "absolute inset-x-0 bottom-0 h-2 bg-gradient-to-t from-[#C5A467]/30 to-transparent" }), _jsx("div", { className: "container relative px-4 md:px-6 z-10", children: _jsxs("div", { className: "flex flex-col items-center space-y-6 text-center", children: [_jsx(GraduationCap, { className: `h-10 w-10 text-[${accentColor}] mb-2` }), _jsx("h2", { className: "text-3xl font-bold tracking-tight sm:text-4xl font-serif", children: "Ready to Begin Your Theological Journey?" }), _jsx("p", { className: "mx-auto max-w-[700px] text-[#E0D6C3] md:text-xl lg:text-lg", children: "Join our next cohort and deepen your understanding of Apostolic and Evangelical theology." }), _jsxs("div", { className: "space-x-4 pt-4", children: [_jsx(Link, { to: "/register", children: _jsx(Button, { size: "lg", className: `bg-[${accentColor}] hover:bg-[${accentHoverColor}] text-[#2A0F0F] font-semibold transition-colors`, children: "Apply Now" }) }), _jsx(Link, { to: "/courses" })] })] }) })] })] }));
}
